name: build

on:
  push:
    branches:
      - build

jobs:

  build:
    # needs: build-windows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10'] # this version is only used for upload.
        cuda-version: ['121']

    steps:
      - uses: actions/checkout@master
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            needbuild:
              - '.github/workflows/**'
              - 'setup.py'
              - 'spconv/csrc/**'
              - 'spconv/algo.py'
              - 'spconv/core.py'
              - 'pyproject.toml'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pep build
        env:
          BOOST_VERSION: boost_1_77_0
        run: |
          python -m pip install build --user
          python -m pip install --upgrade pip twine wheel
          python -m pip install pytest setuptools
          mkdir -p third_party
          wget https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/$BOOST_VERSION.zip -O third_party/boost.zip
          unzip third_party/boost.zip -d third_party/boost

      - name: Build a cuda wheel
        env:
          CUDA_VERSION: ${{ matrix.cuda-version }}
          PYTHON_VERSION: ${{ matrix.python-version }}
          DOCKER_IMAGE: scrin/manylinux2014-cuda:cu${{ matrix.cuda-version }}-devel-1.0.0
          PLAT: ${{ matrix.cuda-version > '123' && 'manylinux_2_28_x86_64' || 'manylinux2014_x86_64' }}
          BOOST_VERSION: boost_1_77_0
        if: |
          (env.CUDA_VERSION != '') && (
            (github.event_name == 'push' && (startsWith(github.ref, 'refs/tags')) ) ||
            (
              (steps.changes.outputs.needbuild == 'true') &&
              (env.PYTHON_VERSION == '3.12')
            )
          )
        run: |
          chmod +x tools/build-wheels.sh
          docker run --rm -e PLAT=$PLAT -e CUMM_CUDA_VERSION=${{ matrix.cuda-version }} \
           -e SPCONV_PYTHON_LIST=${{env.PYTHON_VERSION}} \
           -e BOOST_ROOT=/io/third_party/boost/$BOOST_VERSION \
           -v `pwd`:/io $DOCKER_IMAGE bash -c "source /etc/bashrc && /io/tools/build-wheels.sh"
